version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APACHE_SERVER_NAME=app  
    volumes:
      - ./app:/var/www/html/
